const Strings = {
  texts: {
    rememberPassword: 'Remember Password?',
    logIn: 'Log In',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
    rememberMe: 'Remember me',
    forgetPassword: 'Forget Password?',
    continueAsGuest: 'Continue as guest',
    watchMovies: 'Watch Movies',
    anytimeAnywhere: 'Anytime Anywhere',
    didNotReceivedCode: "Didn't Received Code?",
    alreadyHaveAccount: 'Already have an account?',
    empty: '',
    emptySpace: ' ',
    guest: 'Guest',
    or: 'OR',
    name: 'Name: ',
    Email: 'Email ',
    fastX: 'Fast X',
    newScreen: 'New Screen',
    playTrailer: 'Play Trailer',
    readMore: 'Read More...',
    readLess: 'Read Less',
    noFavorites: 'No favorites yet.',
  },
  separators: {
    pipe: ' | ',
    slash: '/',
  },
  headerTitle: {
    forgetPassword: 'Forget Password',
    logIn: 'Login',
    otp: 'OTP Verification',
    passwordChanged: 'Password Changed',
    newPassword: 'Create New Password',
    signUp: 'Sign Up',
    favorites: 'Favorites',
  },
  headerDescription: {
    dontWorry: "Don't worry! Please enter the",
    emailLinked: 'email linked with your account.',
    welcomeBack: 'Welcome back! Glad to ',
    seeYouAgain: 'see you, Again!',
    enterVerificationCode: 'Enter the verification code we just ',
    sentEmail: 'sent on your email',
    passwordChangedSuccessFully: 'Your Password has been changed successfully',
    newPasswordMustUnique:
      'Your new password must be unique from those previously used.',
    signUp: 'Hello! Sign Up to get ',
    started: 'started',
  },
  errors: {
    name: 'Name is required',
    emailRequired: 'Email is required',
    emailNotRegistered: 'Email not registered',
    emailInvalid: 'Invalid email format',
    passwordRequired: 'Password is required',
    confirmPasswordRequired: 'Confirm Password is required',
    passwordNotMatch: 'Passwords do not match.',
    passwordWeak: 'Password should be at least 6 characters',
    passwordInvalid: 'Password must be 6 chars, include uppercase and number',
    error: 'Error',
    failedToLoadData: 'Failed to load user data',
    failedToUpdateData: 'Failed to update user data',
    noAuthUserFound: 'No authenticated user found.',
    userDataNotFound: 'User data not found.',
    otpExpired: 'This OTP code has expired. Please request again.',
    otpInvalid: 'Invalid OTP record.',
    otpEnterAllDigits: 'Please enter all 4 digits.',
    otpVerificationFailed: 'OTP verification failed.',
    otpIncorrect: 'You entered OTP code is incorrect.',
    otpAlreadyUsed: 'This code has already been used.',
    otpNoRequestFound: 'No OTP request found for this email.',
    googleNoIdTokenReceived: 'No ID token received from Google Sign-In',
    resetPasswordError: 'Unknown error resetting password',
    facebookSomethingWentWrongToken:
      'Something went wrong obtaining Facebook access token',
    appleSignInFailed: 'Apple Sign-In failed',
    passwordResetFailed: 'Failed to request password reset.',
    failedToLoadImage: 'Failed to load image',
    invalidMovieObject: 'Invalid movie object',
    failedToSyncFavorites: 'Failed to sync favorites from Firebase',
    firebaseSyncFailed: 'Firebase sync failed:',
    failedToSaveFavorites: 'Failed to save favorites:',
    failedToAddFavoriteToFirebase: 'Failed to add favorite to Firebase:',
    failedToRemoveFavoriteFromFirebase:
      'Failed to remove favorite from Firebase:',
    failedToRemoveFavorite: 'Failed to remove favorite:',
    failedToCleanupFavorites: 'Failed to cleanup favorites:',
    failedToUpdateFavorites: 'Failed to update favorites',
    errorRemovingFavorite: 'Error removing favorite:',
  },
  alerts: {
    title: {
      logout: 'Logout',
      removeMovie: 'Remove Movie',
    },
    message: {
      areYouWantToLogOut: 'Are you sure you want to logout?',
      areYouWantToRemoveMovie:
        'Are you sure you want to remove this movie from favorites?',
      cleanedFavorites: 'Cleaned up favorites, removed null values',
    },
  },
  buttons: {
    no: 'No',
    yes: 'Yes',
    remove: 'Remove',
    sendCode: 'Send Code',
    logOut: 'Log out',
    logIn: 'Log in',
    signUp: 'Sign up',
    signOut: 'Sign Out',
    google: 'Continue with Google',
    facebook: 'Continue with Facebook',
    apple: 'Continue with Apple',
    verify: 'Verify',
    backToLogin: 'Back to Login',
    resetPassword: 'Reset Password',
    watchNow: 'Watch Now',
  },
  icons: {
    email: 'email',
    logo: 'logo',
    lock: 'lock',
    passwordShow: 'passwordShow',
    google: 'google',
    facebook: 'facebook',
    apple: 'apple',
    lock: 'lock',
    user: 'user',
  },
  inputPlaceholder: {
    email: 'Email',
    password: 'Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    name: 'Name',
  },
  consoleMessage: {
    registerUserFetchedUserData: '[registerUser] Fetched document data:',
    registerUserDocumentDoesNotExist:
      '[registerUser]  Document does not exist right after setDoc',
    requestPasswordReset: 'requestPasswordReset →',
    verifyPasswordReset: 'verifyPasswordResetOTP →',
    confirmPasswordReset: 'confirmPasswordResetWithOTP →',
    googleSignInResponse: 'Google Sign-In response:',
    googleToken: 'ID Token:',
    googleFound: 'Found',
    googleMissing: 'Missing',
    googleSignInError: 'Google Sign-In Error:',
    googleSignInCancelled: 'Sign-in cancelled by user',
    googleSignInInprogress: 'Sign-in already in progress',
    googlePlayServiceNotAvailable: 'Google Play Services not available',
    facebookSignInCancelled: 'Sign-in cancelled by user',
    facebookSignInResult: 'Facebook login result:',
    facebookSignInError: 'Facebook Sign-In Error:',
    useHomeData: 'useHome Data : ',
  },
  section: {
    today: 'Today',
    popularMovies: 'Popular Movies',
    lastMonth: 'Last Month',
    lastSixMonth: 'Last 6 Month',
    synopsis: 'Synopsis',
    cast: 'Cast',
    relatedMovies: 'Related Movies',
  },
};

export default Strings;
